### ISSUE TITLE
Troubles with Travis

### ISSUE THREAD

**Issue by DilumAluthge** [JuliaCI/CoverageTools.jl#14]
There is something weird with the Travis setup on the JuliaCI organization. It’s using `staging.travis-ci.com`, which I think is the experimental version of Travis.

As a result, some things that work on `travis-ci.org` don’t work on `staging.travis-ci.com`. For example, submission to Coveralls works perfectly from `travis-ci.org`, but doesn’t work from `staging.travis-ci.com`.

Could we uninstall `staging.travis-ci.com` from JuliaCI and install the regular Travis (`travis-ci.org`) on all the JuliaCI repositories?

cc: @ararslan @StefanKarpinski

**Comment by ararslan** [comment]
Done, I think.

**Comment by DilumAluthge** [comment]
Does not seem to be working, see e.g. https://github.com/JuliaCI/CoverageCore.jl/pull/15

**Comment by DilumAluthge** [comment]
Can you go here: https://travis-ci.org/JuliaCI/CoverageCore.jl

And try to turn it on?

**Comment by ararslan** [comment]
Done

**Comment by DilumAluthge** [comment]
Now we are cooking with gas.

One last request- can you fix or remove the branch protection settings for the `master` branch of CoverageCore.jl? The current branch protection settings use the incorrect `staging.travis-ci.com` status check.

**Comment by ararslan** [comment]
I kept branch protection but removed the requirement that CI passes.

**Comment by DilumAluthge** [comment]
Perfect!

**Comment by DilumAluthge** [comment]
I think all the problems are fixed now.
